### PR TITLE
Adding es-ES branch.

### PR DESCRIPTION
**Pull request by ccanivell**
@Delizald You might want to review, I will do the same for yours, even though we have some slight language differences.

### CODE REVIEW

**Comment by fangfufu** [comment]
@ccanivell , could you resolve the merge conflict please? I can't read the language, so I am not entirely sure what's going on.

**Comment by ccanivell** [comment]
> @ccanivell , could you resolve the merge conflict please? I can't read the language, so I am not entirely sure what's going on.

@fangfufu I have done it know, looks like the translations from @Delizald  and mines were merging to es-ES at the same time.

Should be OK now.

**Review by fangfufu — APPROVED** [review]

**Comment by fangfufu** [comment]
Thanks, I am merging this. :)

**Comment by ccanivell** [comment]
Thanks! GitHub is giving us a hard day

**Comment by fangfufu** [comment]
@ccanivell, do you have an account on Discord? If so, what's your name on Discord? 

Github had problems today, basically. 
https://www.githubstatus.com/

**Comment by ccanivell** [comment]
Yes, I had seen that.. but glad to see we move forward 

You can find me as ccanivell as well, lucky to have same username🍀

**Pull request merged**
