### PR TITLE
Replaced lint action with validation script

### PR DESCRIPTION
**Pull request by ffissore**
This script does what the previous github action did (verifying yaml file syntax) and it also:
- ensures all required keys are present (with an exception to `home.yaml` which misses the `title` key)
- ensures the `language` key is properly set

### CODE REVIEW

**Review by kn1cht — CHANGES_REQUESTED** [review]
Great!
Since YAMLLint is no longer needed by this change, would you remove `.yamllint` file also?

**Comment by fangfufu** [comment]
~~@kn1cht / @ffissore , it is still failing to validate.~~
Ah, got it, need to fix ko-KR.

**Comment by kn1cht** [comment]
> Missing 'title' key in Localization/ko-KR/home.yaml

@ffissore Would you fix this? (same change as #50 I think)

**Review by fangfufu — APPROVED** [review]

**Review by fangfufu — APPROVED** [review]

**Review by fangfufu — APPROVED** [review]

**Comment by kn1cht** [comment]
@ffissore 
> Great!
> Since YAMLLint is no longer needed by this change, would you remove `.yamllint` file also?

**Review by fangfufu — APPROVED** [review]

**Review by fangfufu — APPROVED** [review]
I approve these changes.

**Review by fangfufu — APPROVED** [review]

**Comment by kn1cht** [comment]
> @ffissore
> 
> > Great!
> > Since YAMLLint is no longer needed by this change, would you remove `.yamllint` file also?

@ffissore / @fangfufu removing .yamllint does not have to be done right now, so should I approve this PR now?

**Comment by fangfufu** [comment]
@kn1cht , yes please approve.

**Review by kn1cht — APPROVED** [review]

**Comment by ffissore** [comment]
Thx folks

**Pull request merged**
