### PR TITLE
Updates on es-MX

### PR DESCRIPTION
**Pull request by Delizald**

### CODE REVIEW

**Comment by Delizald** [comment]
Please wait, seems I need to corect some files first

**Comment by tematim** [comment]
Inside About.po file, you need to remove the double quote near 'las "proteínas'

**Comment by tematim** [comment]
Inside home.po you removed 'msgid ' before '"For tech support: [foldingforum.org](https://foldingforum.org/)"', add it again and the file will be ok

**Review by meatball133 — COMMENTED** [review]
Home has 
msgid "foldingforum.org"
msgstr "foldingforum.org"
these needs to be removed.
Also update the target date when you update the file and not the exact same date as the source version aslong as you didn't update the target the excat same date. I understand now in after hand you don't know the excat date. I just say this until next time. Othervise really good job

**Review by meatball133 — APPROVED** [review]

**Comment by meatball133** [comment]
Good job

**Pull request merged**
