### PR TITLE
trans: translate about page in fr-FR

### PR DESCRIPTION
**Pull request by SteadEXE**

### CODE REVIEW

**Comment by fangfufu** [comment]
@Antonthynell, do you want to merge this as well? I will edit it into YAML format, then do another pull request.

**Comment by SteadEXE** [comment]
Sure we can move to YAML format if you want.

**Comment by fangfufu** [comment]
@SteadEXE, Anton has already merged my YAML pull request already. So it has to be converted into YAML format. 

I am happy to convert your existing contribution to YAML format, if Anton merged this pull request. Alternatively you can close this pull request, update your fork, then convert your contribution to YAML format. 

Let us know what you prefer to do. :)

**Comment by Antonthynell** [comment]
Yes do kindly convert it to YAML format

**Comment by fangfufu** [comment]
@SteadEXE , I converted your translation into YAML format. It is now in the pull request.

**Pull request merged**
