### PR TITLE
New files

### PR DESCRIPTION
**Pull request by meatball133**

### CODE REVIEW

**Comment by ReadyPlayerEmma** [comment]
This looks good, but can you change that note. Let's pull it out of there for now please. Then we can merge this I think.

**Review by ReadyPlayerEmma — DISMISSED** [review]
Looks good to me now.

**Comment by ReadyPlayerEmma** [comment]
I guess it makes sense we don't need the target language stuff in there for en-US

**Review by ReadyPlayerEmma — DISMISSED** [review]

**Review by ReadyPlayerEmma — APPROVED** [review]

**Review by ReadyPlayerEmma — DISMISSED** [review]
The check seems flawed, the "NOTE" is gone now... but somehow the check thinks it is not?

**Comment by meatball133** [comment]
Idk i am not good at these kinds of things

**Comment by meatball133** [comment]
I opened the file with poedit and it does not show an errors

**Comment by meatball133** [comment]
any*

**Comment by meatball133** [comment]
you solved it somehow

**Review by ReadyPlayerEmma — APPROVED** [review]
Nevermind, but it is fixed now xD

**Pull request merged**
